version: '3.8'

services:
  rowt-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rowt-ui
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rowt-ui.rule=Host(`ui.rowt.local`)"
      - "traefik.http.routers.rowt-ui.entrypoints=web"
      - "traefik.http.services.rowt-ui.loadbalancer.server.port=80"

  # Optional: Add a reverse proxy for production
  nginx-proxy:
    image: nginx:alpine
    container_name: rowt-ui-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - rowt-ui
    restart: unless-stopped
    profiles:
      - proxy

networks:
  default:
    name: rowt-network
    external: false
