version: '3.8'

services:
  rowt-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rowt-ui
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.rowt-ui.rule=Host(`rowt-ui.localhost`)"
      - "traefik.http.services.rowt-ui.loadbalancer.server.port=80"
    networks:
      - rowt-network

  # Optional: Add a development service for local development
  rowt-ui-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rowt-ui-dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: unless-stopped
    profiles:
      - dev
    networks:
      - rowt-network

networks:
  rowt-network:
    driver: bridge
    name: rowt-network
