# Docker Compose override for development
# This file is automatically loaded by docker-compose for local development

version: '3.8'

services:
  rowt-ui-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_MODE=development
    container_name: rowt-ui-dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # For file watching in Docker
    command: npm run dev
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - rowt-network
