# Docker Compose override for development
# This file is automatically loaded by docker-compose for local development

version: '3.8'

services:
  rowt-ui:
    build:
      args:
        - BUILD_MODE=development
        - NODE_ENV=development
    ports:
      - "${DEV_PORT:-8080}:8080"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    environment:
      - NODE_ENV=development
      - BUILD_MODE=development
      - CHOKIDAR_USEPOLLING=true
      - HOST_PORT=8080
      - CONTAINER_PORT=8080
    stdin_open: true
    tty: true
